endpoint: 'https://api.spire.com/graphql'
token: ""
name_of_gql_query_file: 'sample_1.txt'
name_of_raw_output_file: ''   # if set to "" no file will be produced
name_of_csv_file: 'parsed.csv' # if set to "" no file will be produced
pages_to_process: 5  # if 0, then all pages.  Otherwise this is used to limit the pages processed


